-- Optional starter gatherings. Run in the Supabase SQL editor (runs as an admin, so RLS is bypassed).
-- Slugs are generated by the database. Adjust the dates, they're examples.
insert into public.events (title, theme, description, starts_at) values
  ('Harvest Table', 'Everything from the autumn garden',
   'Squash, apples, late tomatoes and good bread. Bring something that grew nearby, and a chair if you have a spare.',
   '2026-10-17 18:00:00-07'),
  ('Soup Swap Sunday', 'Cozy pots & ladles',
   'Bring a big pot of soup and jars to take some home.',
   '2026-11-15 16:00:00-08'),
  ('Late Summer Porch Supper', 'Tomatoes, corn & lemonade',
   'A long evening on the porch with everything the market had left.',
   '2026-09-05 18:30:00-07');
